### ISSUE TITLE
No module named 'robot_flamingo'

### ISSUE THREAD

**Issue by emrecanacikgoz** [RoboFlamingo/RoboFlamingo#13]
Hi,

When I follow the provided instructions to set the repo and try for training, I am facing the error below:

```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "robot_flamingo/train/train_calvin.py", line 16, in <module>
    from robot_flamingo.data.data import get_data
  File "robot_flamingo/train/train_calvin.py", line 16, in <module>
Traceback (most recent call last):
ModuleNotFoundError: No module named 'robot_flamingo'
  File "robot_flamingo/train/train_calvin.py", line 16, in <module>
    from robot_flamingo.data.data import get_data
ModuleNotFoundError: No module named 'robot_flamingo'
    from robot_flamingo.data.data import get_data
ModuleNotFoundError: No module named 'robot_flamingo'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 33566) of binary: /kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo/bin/python
Traceback (most recent call last):
  File "/kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
robot_flamingo/train/train_calvin.py FAILED
------------------------------------------------------------
```

Below is the environment info:
```
(RoboFlamingo) [eacikgoz17@login03 RoboFlamingo]$ conda list
# packages in environment at /kuacc/users/eacikgoz17/.conda/envs/RoboFlamingo:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
aiohttp                   3.9.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
ca-certificates           2023.12.12           h06a4308_0  
calvin                    0.0.1                     dev_0    <develop>
calvin-env                0.0.1                    pypi_0    pypi
certifi                   2023.11.17               pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
cmake                     3.18.4                   pypi_0    pypi
colorlog                  6.8.2                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
einops-exts               0.0.4                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
filelock                  3.12.4                   pypi_0    pypi
flamingo-pytorch          0.1.2                    pypi_0    pypi
fonttools                 4.47.2                   pypi_0    pypi
freetype-py               2.4.0                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2023.12.2                pypi_0    pypi
ftfy                      6.1.3                    pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.41                   pypi_0    pypi
gym                       0.26.2                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
huggingface-hub           0.18.0                   pypi_0    pypi
hydra-colorlog            1.2.0                    pypi_0    pypi
hydra-core                1.1.1                    pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imageio                   2.31.5                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lightning-lite            1.8.6                    pypi_0    pypi
lightning-utilities       0.10.1                   pypi_0    pypi
llvmlite                  0.41.1                   pypi_0    pypi
lxml                      5.1.0                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
matplotlib                3.7.4                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
moviepy                   1.0.3                    pypi_0    pypi
multicoretsne             0.1                      pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  2.2                      pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numba                     0.58.1                   pypi_0    pypi
numcodecs                 0.12.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpy-quaternion          2022.4.3                 pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.1.2                    pypi_0    pypi
open-clip-torch           2.20.0                   pypi_0    pypi
opencv-python             3.4.8.29                 pypi_0    pypi
openssl                   3.0.12               h7f8727e_0  
packaging                 23.2                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.3.1           py38h06a4308_0  
plotly                    5.18.0                   pypi_0    pypi
portalocker               2.8.2                    pypi_0    pypi
proglog                   0.1.10                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pycollada                 0.6                      pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyglet                    2.0.10                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyhash                    0.9.3                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pyrender                  0.1.45                   pypi_0    pypi
python                    3.8.18               h955ad1f_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-lightning         1.8.6                    pypi_0    pypi
pytorch3d                 0.3.0                    pypi_0    pypi
pytz                      2023.4                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
regex                     2023.5.5                 pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
responses                 0.18.0                   pypi_0    pypi
rich                      13.3.5                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
sacremoses                0.0.53                   pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
sentence-transformers     2.2.2                    pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.40.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                57.5.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
svgwrite                  1.4.3                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tacto                     0.0.3                     dev_0    <develop>
tenacity                  8.2.3                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
timm                      0.9.12                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
torchaudio                0.12.1                   pypi_0    pypi
torchmetrics              1.3.0.post0              pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.33.1                   pypi_0    pypi
tree                      0.2.4                    pypi_0    pypi
trimesh                   4.1.0                    pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2023.4                   pypi_0    pypi
urdfpy                    0.0.22                   pypi_0    pypi
urllib3                   2.2.0                    pypi_0    pypi
wandb                     0.15.2                   pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0  
xz                        5.4.5                h5eee18b_0  
yacs                      0.1.8                    pypi_0    pypi
yarl                      1.9.2                    pypi_0    pypi
zarr                      2.15.0                   pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
```

If its help, below is my top-level path tree:
```
checkpoints                   
eval_sequences.json         
LICENSE   
open_flamingo           
requirements.txt  
train.sh
assets      
enrich_lang_annotations.json  
eval.sh                     
load.py   
partial_task_data.json  
robot_flamingo
calvin      
eval_ckpts.py                 
lang_annotation_cache.json  
logs_new  
README.md               
RobotFlamingoDBG
```
Finally my train run command:
```
torchrun --nnodes=1 --nproc_per_node=3 --master_port=6042 robot_flamingo/train/train_calvin.py \
    --report_to_wandb \
    --llm_name mpt_dolly_3b \
    --traj_cons \
    --use_gripper \
    --fusion_mode post \
    --rgb_pad 10 \
    --gripper_pad 4 \
    --precision fp32 \
    --num_epochs 5 \
    --gradient_accumulation_steps 1 \
    --batch_size_calvin 6 \
    --run_name RobotFlamingoDBG \
    --calvin_dataset /datasets/calvin_new/task_ABCD_D \
    --openflamingo_checkpoint RoboFlamingo/RobotFlamingoDBG/checkpoint_gripper_post_hist_1_aug_10_4_traj_cons_ws_12_mpt_3b_4.pth \
    --cross_attn_every_n_layers 4 \
    --dataset_resampled \
    --loss_multiplier_calvin 1.0 \
    --workers 1 \
    --lr_scheduler constant \
    --warmup_steps 5000 \
    --learning_rate 1e-4 \
    --save_every_iter 10000 \
    --from_scratch \
```
Could you please help me for that path issue?

**Comment by Ericonaldo** [comment]
Hi. Are you running the command from the parent directory of the `robot_flamingo` directory?

If so and it still not work, you can try to add the path into the python sys.path, in your bash or add a code to the training script:
```
import sys
sys.path.append('/path/to/the/directory')
```

**Comment by emrecanacikgoz** [comment]
Issue solved, thank you.
