### ISSUE TITLE
Exception in thread Thread-1:

### ISSUE THREAD

**Issue by le-wei** [RoboFlamingo/RoboFlamingo#2]
Hello,

Thank you very much for open-sourcing such an interesting project. I followed the prompt steps and conducted a test. However, there was an error during the rendering process, which caused the thread to die. The log is as follows:

**[2023-11-09 11:52:33,764] torch.distributed.run: [WARNING] 
[2023-11-09 11:52:33,764] torch.distributed.run: [WARNING] *****************************************
[2023-11-09 11:52:33,764] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-11-09 11:52:33,764] torch.distributed.run: [WARNING] *****************************************
pybullet build time: May 20 2022 19:44:17
pybullet build time: May 20 2022 19:44:17
device_id:  cuda:1
world_size:  2
device_id:  cuda:0
world_size:  2
Using pad_token, but it is not set yet.
/home/ubuntu/objectData/RoboFlamingo/RoboFlamingo/open_flamingo/mpt-1b-redpajama-200b
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Using pad_token, but it is not set yet.
/home/ubuntu/objectData/RoboFlamingo/RoboFlamingo/open_flamingo/mpt-1b-redpajama-200b
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
WARNING:py.warnings:/home/ubuntu/.cache/huggingface/modules/transformers_modules/mpt-1b-redpajama-200b/attention.py:289: UserWarning: Using `attn_impl: torch`. If your model does not use `alibi` or `prefix_lm` we recommend using `attn_impl: flash` otherwise we recommend using `attn_impl: triton`.
  warnings.warn(

WARNING:py.warnings:/home/ubuntu/.cache/huggingface/modules/transformers_modules/mpt-1b-redpajama-200b/attention.py:289: UserWarning: Using `attn_impl: torch`. If your model does not use `alibi` or `prefix_lm` we recommend using `attn_impl: flash` otherwise we recommend using `attn_impl: triton`.
  warnings.warn(

You are using config.init_device='cpu', but you can also use config.init_device="meta" with Composer + FSDP for fast initialization.
You are using config.init_device='cpu', but you can also use config.init_device="meta" with Composer + FSDP for fast initialization.
window size: 12
1024 2048
MosaicGPTConfig {
  "_name_or_path": "/home/ubuntu/objectData/RoboFlamingo/RoboFlamingo/open_flamingo/mpt-1b-redpajama-200b",
  "alibi": true,
  "alibi_bias_max": 8,
  "architectures": [
    "MosaicGPT"
  ],
  "attn_clip_qkv": null,
  "attn_impl": "torch",
  "attn_pdrop": 0,
  "attn_qk_ln": true,
  "attn_uses_sequence_id": false,
  "auto_map": {
    "AutoConfig": "configuration_mosaic_gpt.MosaicGPTConfig",
    "AutoModelForCausalLM": "mosaic_gpt.MosaicGPT"
  },
  "d_model": 2048,
  "emb_init_std": null,
  "emb_init_uniform_lim": null,
  "emb_pdrop": 0,
  "embedding_fraction": 1.0,
  "fan_mode": "fan_in",
  "init_device": "cpu",
  "init_div_is_residual": true,
  "init_gain": 0,
  "init_nonlinearity": "relu",
  "init_std": 0.02,
  "logit_scale": null,
  "low_precision_layernorm": true,
  "max_seq_len": 2048,
  "mlp_ratio": 4,
  "model_type": "mosaic_gpt",
  "n_heads": 16,
  "n_layers": 24,
  "no_bias": true,
  "param_init_fn": "kaiming_normal_",
  "prefix_lm": false,
  "resid_pdrop": 0,
  "softmax_scale": null,
  "tokenizer_name": "EleutherAI/gpt-neox-20b",
  "torch_dtype": "float32",
  "transformers_version": "4.28.1",
  "use_cache": false,
  "verbose": 0,
  "vocab_size": 50280
}

window size: 12
1024 2048
MosaicGPTConfig {
  "_name_or_path": "/home/ubuntu/objectData/RoboFlamingo/RoboFlamingo/open_flamingo/mpt-1b-redpajama-200b",
  "alibi": true,
  "alibi_bias_max": 8,
  "architectures": [
    "MosaicGPT"
  ],
  "attn_clip_qkv": null,
  "attn_impl": "torch",
  "attn_pdrop": 0,
  "attn_qk_ln": true,
  "attn_uses_sequence_id": false,
  "auto_map": {
    "AutoConfig": "configuration_mosaic_gpt.MosaicGPTConfig",
    "AutoModelForCausalLM": "mosaic_gpt.MosaicGPT"
  },
  "d_model": 2048,
  "emb_init_std": null,
  "emb_init_uniform_lim": null,
  "emb_pdrop": 0,
  "embedding_fraction": 1.0,
  "fan_mode": "fan_in",
  "init_device": "cpu",
  "init_div_is_residual": true,
  "init_gain": 0,
  "init_nonlinearity": "relu",
  "init_std": 0.02,
  "logit_scale": null,
  "low_precision_layernorm": true,
  "max_seq_len": 2048,
  "mlp_ratio": 4,
  "model_type": "mosaic_gpt",
  "n_heads": 16,
  "n_layers": 24,
  "no_bias": true,
  "param_init_fn": "kaiming_normal_",
  "prefix_lm": false,
  "resid_pdrop": 0,
  "softmax_scale": null,
  "tokenizer_name": "EleutherAI/gpt-neox-20b",
  "torch_dtype": "float32",
  "transformers_version": "4.28.1",
  "use_cache": false,
  "verbose": 0,
  "vocab_size": 50280
}

Flamingo model initialized with 1088187703 trainable parameters
Loading origin flamingo checkpoint from  /home/ubuntu/objectData/RoboFlamingo/RoboFlamingo/open_flamingo/OpenFlamingo-3B-vitl-mpt1b/checkpoint.pt
Flamingo model initialized with 1088187703 trainable parameters
Loading origin flamingo checkpoint from  /home/ubuntu/objectData/RoboFlamingo/RoboFlamingo/open_flamingo/OpenFlamingo-3B-vitl-mpt1b/checkpoint.pt
Loading robot-flamingo checkpoint from /home/ubuntu/objectData/RoboFlamingo/RoboFlamingo/checkpoint_gripper_post_hist_1_aug_10_4_traj_cons_ws_12_mpt_3b_2.pth
argv[0]=--width=200
argv[1]=--height=200
argv[0]=--width=200
argv[1]=--height=200
EGL device choice: -1 of 7.
EGL device choice: -1 of 7.
Loaded EGL 1.5 after reload.
Loaded EGL 1.5 after reload.
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce RTX 4090/PCIe/SSE2
GL_VERSION=4.6.0 NVIDIA 535.129.03
GL_SHADING_LANGUAGE_VERSION=4.60 NVIDIA
Version = 4.6.0 NVIDIA 535.129.03
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 4090/PCIe/SSE2
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce RTX 4090/PCIe/SSE2
GL_VERSION=4.6.0 NVIDIA 535.129.03
GL_SHADING_LANGUAGE_VERSION=4.60 NVIDIA
Version = 4.6.0 NVIDIA 535.129.03
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 4090/PCIe/SSE2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer_mp.py", line 13, in worker
    renderer = _Renderer(width, height, background, config_path)
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer.py", line 106, in __init__
    self._init_pyrender()
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer.py", line 146, in _init_pyrender
    colors, depths = self.render(object_poses=None, noise=False, calibration=False)
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer.py", line 568, in render
    color, depth = self.r.render(self.scene, flags=self.flags_render)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/renderer.py", line 144, in render
    retval = self._forward_pass(scene, flags, seg_node_map=seg_node_map)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/renderer.py", line 369, in _forward_pass
    program = self._get_primitive_program(
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/renderer.py", line 1000, in _get_primitive_program
    program._add_to_context()
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/shader_program.py", line 137, in _add_to_context
    self._program_id = gl_shader_utils.compileProgram(*shader_ids)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/OpenGL/GL/shaders.py", line 206, in compileProgram
    program.check_validate()
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/OpenGL/GL/shaders.py", line 106, in check_validate
    raise RuntimeError(
RuntimeError: Validation failure (0): 
  Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer_mp.py", line 13, in worker
    renderer = _Renderer(width, height, background, config_path)
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer.py", line 106, in __init__
    self._init_pyrender()
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer.py", line 146, in _init_pyrender
    colors, depths = self.render(object_poses=None, noise=False, calibration=False)
  File "/home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto/tacto/renderer.py", line 568, in render
    color, depth = self.r.render(self.scene, flags=self.flags_render)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/renderer.py", line 144, in render
    retval = self._forward_pass(scene, flags, seg_node_map=seg_node_map)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/renderer.py", line 369, in _forward_pass
    program = self._get_primitive_program(
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/renderer.py", line 1000, in _get_primitive_program
    program._add_to_context()
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/pyrender/shader_program.py", line 137, in _add_to_context
    self._program_id = gl_shader_utils.compileProgram(*shader_ids)
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/OpenGL/GL/shaders.py", line 206, in compileProgram
    program.check_validate()
  File "/home/ubuntu/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/OpenGL/GL/shaders.py", line 106, in check_validate
    raise RuntimeError(
RuntimeError: Validation failure (0): 
**

The environment I am using is as follows:

**
Package                  Version            Editable project location
------------------------ ------------------ ------------------------------------------------------------
aiohttp                  3.8.6
aiosignal                1.3.1
antlr4-python3-runtime   4.9.3
anyio                    4.0.0
appdirs                  1.4.4
asciitree                0.3.3
astor                    0.8.1
async-timeout            4.0.3
attrs                    23.1.0
boto3                    1.28.82
botocore                 1.31.82
bottle                   0.12.25
braceexpand              0.1.7
Calvin                   0.0.1              /home/ubuntu/objectData/RoboFlamingo/calvin/calvin_models
calvin-env               0.0.1              /home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env
certifi                  2023.7.22
cffi                     1.16.0
charset-normalizer       3.3.2
click                    8.1.7
cloudpickle              3.0.0
cmake                    3.18.4
colorlog                 6.7.0
common                   0.1.2
contourpy                1.1.1
cycler                   0.12.1
data                     0.4
decorator                4.4.2
docker-pycreds           0.4.0
dual                     0.0.10
dynamo3                  0.4.10
einops                   0.6.1
einops-exts              0.0.4
entrypoints              0.4
exceptiongroup           1.1.3
fasteners                0.18
ffmpeg                   1.4
filelock                 3.12.4
flamingo-pytorch         0.1.2
flywheel                 0.5.4
fonttools                4.44.0
freetype-py              2.4.0
frozenlist               1.4.0
fsspec                   2023.10.0
ftfy                     6.1.1
funcsigs                 1.0.2
fvcore                   0.1.5.post20221221
gitdb                    4.0.11
GitPython                3.1.40
gym                      0.26.2
gym-notices              0.0.8
h11                      0.14.0
h5py                     3.10.0
httpcore                 1.0.1
httpx                    0.25.1
huggingface-hub          0.18.0
hydra-colorlog           1.2.0
hydra-core               1.1.1
idna                     3.4
imageio                  2.31.5
imageio-ffmpeg           0.4.8
importlib-metadata       6.8.0
importlib-resources      6.1.1
iopath                   0.1.10
Jinja2                   3.1.2
jmespath                 1.0.1
joblib                   1.2.0
kiwisolver               1.4.5
lightning-lite           1.8.6
lightning-utilities      0.9.0
lit                      17.0.4
llvmlite                 0.41.1
lxml                     4.9.3
markdown-it-py           2.2.0
MarkupSafe               2.1.3
matplotlib               3.7.3
mdurl                    0.1.2
moviepy                  1.0.3
mpmath                   1.3.0
MulticoreTSNE            0.1
multidict                6.0.4
networkx                 2.2
nltk                     3.8.1
numba                    0.58.1
numcodecs                0.12.1
numpy                    1.23.0
numpy-quaternion         2022.4.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu11        8.5.0.96
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu11        10.9.0.58
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu11       10.2.10.91
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu11     11.7.4.91
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu11         2.14.3
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.52
nvidia-nvtx-cu11         11.7.91
nvidia-nvtx-cu12         12.1.105
nvidia-pyindex           1.0.9
oauthlib                 3.2.2
omegaconf                2.3.0
open-clip-torch          2.20.0
open-flamingo            2.0.1
opencv-python            3.4.8.29
opt-einsum               3.3.0
packaging                23.2
paddle                   1.0.2
paddlepaddle             2.5.2
pandas                   2.0.3
pathtools                0.1.2
peewee                   3.17.0
Pillow                   9.5.0
pip                      23.3
plotly                   5.18.0
portalocker              2.8.2
proglog                  0.1.10
protobuf                 3.20.3
prox                     0.0.17
psutil                   5.9.6
pyasn1                   0.5.0
pybullet                 3.2.5
pycollada                0.6
pycparser                2.21
pygame                   2.5.2
pyglet                   2.0.10
Pygments                 2.16.1
pyhash                   0.9.3
PyOpenGL                 3.1.0
PyOpenGL-accelerate      3.1.7
pyparsing                3.1.1
pyrender                 0.1.45
PySocks                  1.7.1
python-dateutil          2.8.2
python-geoip-python3     1.3
pytorch-lightning        1.8.6
pytorch3d                0.3.0
pytz                     2023.3.post1
PyWavelets               1.4.1
PyYAML                   6.0.1
regex                    2023.5.5
requests                 2.31.0
requests-oauthlib        1.3.1
responses                0.18.0
rich                     13.3.5
rsa                      4.9
s3transfer               0.7.0
sacremoses               0.0.53
safetensors              0.4.0
scikit-image             0.19.3
scikit-learn             1.2.2
scipy                    1.5.2
sentence-transformers    2.2.2
sentencepiece            0.1.98
sentry-sdk               1.34.0
setproctitle             1.3.3
setuptools               57.5.0
six                      1.16.0
smmap                    5.0.1
sniffio                  1.3.0
sympy                    1.12
tabulate                 0.9.0
tacto                    0.0.3              /home/ubuntu/objectData/RoboFlamingo/calvin/calvin_env/tacto
tenacity                 8.2.3
tensorboardX             2.6.2.2
termcolor                2.3.0
threadpoolctl            3.2.0
tifffile                 2023.7.10
tight                    0.1.0
timm                     0.9.10
tokenizers               0.13.3
torch                    2.1.0
torchaudio               2.1.0
torchdata                0.7.0
torchmetrics             1.2.0
torchtext                0.16.0
torchvision              0.16.0
tqdm                     4.66.1
transformers             4.28.1
trimesh                  4.0.3
triton                   2.1.0
typing_extensions        4.8.0
tzdata                   2023.3
urdfpy                   0.0.22
urllib3                  1.26.18
wandb                    0.15.2
wcwidth                  0.2.9
webdataset               0.2.73
wheel                    0.41.2
yacs                     0.1.8
yarl                     1.9.2
zarr                     2.15.0
zipp                     3.17.0
**

I hope you can take some valuable time to give me some suggestions. Thank you very much.

**Comment by lixinghang12** [comment]
It seems like a rendering error in CALVIN environment, you can visualize the rendering results from CALVIN and make sure the rendered observations are correct and start the evaluation. In our local evaluation (with A100 80G and V100 32G GPUs), we install dependencies in `robot_flamingo/pt_eval_ckpts.bash` and `export MESA_GL_VERSION_OVERRIDE=4.1` and solves the rendering problem, you may follow our steps and find the correct `MESA_GL_VERSION_OVERRIDE` version for the RTX4090.

**Comment by Ericonaldo** [comment]
Is your problem solved? @le-wei

**Comment by le-wei** [comment]
@Ericonaldo 
Sorry, I modified the MESA_GL_VERSION_OVERRIDE parameter but it still didn't render. As I have other work to do, I haven't had time to research how to solve this. If you have a good solution, please share it. Thank you.

**Comment by Joker-all** [comment]
I also encountered the same problem, visualization error, I changed the export MESA_ GL_ VERSION_ OverRIDE value, still reporting the same error, GPU using INIDIA TITAN RTX.

**Comment by Ericonaldo** [comment]
https://github.com/mees/calvin/issues/11, can check if this works.

I think it may be due to the mismatch between the Pybullet and OpenGL versions. Can you check if these packages' version is matched? Or install the same OpenGL version as shown in `robot_flamingo/pt_eval_ckpts.bash`.

**Comment by sunchurui** [comment]
I encountered the same problem, and I haven't found a solution either.

**Comment by trapoom555** [comment]
I got it working by deleting `os.environ['PYOPENGL_PLATFORM'] = 'osmesa'` in `robot_flamingo/eval/eval_utils.py`.
